name: mlp-2021
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - datasets
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - nltk
  - pytorch
  - seaborn
  - gensim
  - wandb # experiment mgr
  - pytest
  - pyhamcrest